<a href="https://colab.research.google.com/github/Lanchenba-Mayanglambam/Data_Science-Amit-Sir/blob/main/lect_6_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
# pandas

import pandas as pd

dct = {
    "name":["Lanchenba","LB","Tomba","Chaoba"],
    "age":[12,34,21,19],
    "roll no":[1,2,3,4]
}

df = pd.DataFrame(dct,index=['a','b','c','d'])
df
# print(df)
display(df)

        name  age  roll no
a  Lanchenba   12        1
b         LB   34        2
c      Tomba   21        3
d     Chaoba   19        4

In [16]:
df = pd.read_csv("student_data.csv")

# head by default gives first five data
df.head()



# info gives meta data (data of data)
df.info()



# describe gives analysis of the data
df.describe()
# quartile1 : 25% - median of starting to median
# quartile2 : 50% - median
# quartile3 : 75% - median of median to last

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score
count,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000
mean,5.989600,69.88460,6.498500,6.062600,9.988400,64.91100,86.704207
std,3.163589,17.61653,1.709354,3.138163,6.034145,17.50302,15.058383
min,1.000000,40.00000,4.000000,1.000000,0.000000,35.00000,26.670000
25%,3.000000,55.00000,5.000000,3.000000,5.000000,50.00000,76.727500
50%,6.000000,70.00000,6.500000,6.000000,10.000000,65.00000,92.120000
75%,9.000000,85.00000,8.000000,9.000000,15.000000,80.00000,100.000000
max,11.000000,100.00000,9.000000,11.000000,20.000000,95.00000,100.000000

In [46]:
df = pd.read_csv("student_data.csv")
# df.tail(3)

# display(df.index)


# to print out specific column
df[['study_hours',"attendance"]]
# df.study_hours





# loc works on labels
# iloc works on index

# iloc is used to access to a specific row
df.iloc[0:5]

# loc takes a condition then it can access through required row and column
df.loc[df["study_hours"] == 11, ['study_hours','sleep_hours']].iloc[0:5]
# or
df2 = df.loc[df['study_hours'] == 11]
df2[['study_hours','study_hours']]
df2.iloc[0:5]

# loc also takes index if the given index is present in the data and iloc makes it's own index
display(df.loc[4])

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
2,11,60,7,6,10,45,100.00,Placed
9,11,77,4,9,15,69,100.00,Placed
10,11,64,8,8,12,76,100.00,Placed
29,11,63,9,10,1,72,96.59,Placed
30,11,45,5,2,4,93,100.00,Placed

In [53]:
df = pd.read_csv("student_data.csv")
df.loc[df['assignments_completed'] == 8].iloc[1:2]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
4,5,52,8,6,8,40,78.82,Placed

In [106]:
df = pd.read_csv("student_data.csv")

df[df["assignments_completed"] > 3]

# rename columns
# rename makes a copy of the file with the changes
# "inplace = True" change in the original file
df.rename(columns={'assignments_completed': 'assign_completed'},inplace=True)
# df





# Remove rows or columns
df.drop('assign_completed',axis=1,inplace=True)  # removes column
df.drop(0,axis=0,inplace=True)  # removes row
df




# Remove missing values
dct = {
    "name":["Lanchenba","LB","Tomba","Chaoba"],
    "age":[12,34,21,19],
    "roll no":[1,2,3,None]
}
a = pd.DataFrame(dct,index=[1,2,3,4])
display(a)
# use axis = 0/1 to removes colums wise or row wise
# a.dropna(inplace=True)
# a





# Check for missing values
# isnull gives answer in bool if values are present then false otherwise true
a.isnull()

# Check for non-missing values
# notnull gives answer in bool if values are present then true otherwise false
a.notnull()

        name  age  roll no
1  Lanchenba   12      1.0
2         LB   34      2.0
3      Tomba   21      3.0
4     Chaoba   19      NaN

   name   age  roll no
1  True  True     True
2  True  True     True
3  True  True     True
4  True  True    False

In [109]:
df = pd.read_csv("student_data.csv")

# Unique
# it works only in series
df["sleep_hours"].unique()

array([8, 5, 7, 9, 4, 6])